sudo: required
services:
  docker

before_install:
  - docker build -t anunirva777/frontend-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true anunirva777/frontend-test npm test

after_success:
  - docker build -t anunirva777/multi-client ./client
  - docker build -t anunirva777/multi-nginx ./nginx
  - docker build -t anunirva777/multi-server ./server
  - docker build -t anunirva777/multi-worker ./worker
  # Login to Docker CLI
  # store credentials username/password to env variables in travis CI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Now push these prod images to docker hub
  - docker push anunirva777/multi-client
  - docker push anunirva777/multi-nginx
  - docker push anunirva777/multi-server
  - docker push anunirva777/multi-worker