version: '3'
services: 
  postgres_service:
    image: 'postgres:latest'
    environment: 
      - POSTGRES_PASSWORD=postgres_password
  redis_service:
    image: 'redis:latest'
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - '8080:80'
  api:
    depends_on: 
      - postgres_service
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment: 
      - REDIS_PORT=6379
      - REDIS_HOST=redis_service
      - PGUSER=postgres 
      - PGPASSWORD=postgres_password
      - PGHOST=postgres_service      
      - PGPORT=5432       
      - PGDATABASE=postgres
  client:
    stdin_open: true
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
      - /app/node_modules
      - ./worker:/app
    environment: 
      - REDIS_HOST=redis_service
      - REDIS_PORT=6379
